version: '3'
services:

  nginx:
    image: nginx:alpine
    container_name: nginx1
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: /home/jon/bind-mount
        target: /usr/share/nginx/html