---
# This playbook configures OU on an AD
- name: windows-createOU
  hosts: domain_controller
  gather_facts: no
  
  tasks:
  - name: load from jinja template
    win_template:
      src: files/windows/createOU.ps1.j2
      dest: C:\480\createOU.ps1
  - name: run the script
    async: 10
    poll: 0
    win_shell: 
      C:\480\createOU.ps1